apiVersion: training.eduk8s.io/v1alpha2
kind: Workshop
metadata:
  name: lab-terminal-hacks
spec:
  title: Terminal Hacks
  description: Workshop image to develop new terminal
  content:
    image: quay.io/eduk8s-tests/lab-terminal-hacks:master
  session:
    budget: small
    dashboards:
    - name: "MyTerminal"
      url: /myterminal
