#!/bin/bash
set -x

set -eo pipefail

# Always recalculate the workshop directory in case running this due
# to it being restarted within the context of the container.

TERMINAL_PORT=${TERMINAL_PORT:-10191}
TERMINAL_TARGET_DIR=${TERMINAL_TARGET_DIR:-"/home/eduk8s/"}

ARGS=""

ARGS="$ARGS --cwd=$TERMINAL_TARGET_DIR"
ARGS="$ARGS --port=$TERMINAL_PORT"

exec node ./terminal.js $ARGS